version: 2

build: &build
  docker:
    - image: circleci/ruby:2
  environment:
    TERM: xterm
    SRC_REPO: /home/circleci/project
    GVM_NO_GIT_BAK: 1
    GVM_NO_UPDATE_PROFILE: 1
  steps:
    - checkout
    - run: sudo apt-get -y install --no-install-recommends curl git mercurial make binutils bison gcc build-essential
    - run: binscripts/gvm-installer ${CIRCLE_SHA1} ./tmp
    - run: gem install tf -v '>=0.4.1' --no-document
    - run: source ./tmp/gvm/scripts/gvm; rake default scenario

jobs:
  build:
    <<: *build

workflows:
  version: 2
  build:
    jobs:
      - build